meta_db <- data.frame(
  Participants = c("Patients with depression following TBI; 12 studies", 
                   "844 patients", 
                   "Participants from 12 RCTs", 
                   "1003 medical students", 
                   "Sample from 10 studies"),
  Intervention = c("Pharmacological treatments", 
                   "Point-of-care ocular ultrasound", 
                   "Alpha-lipoic acid (ALA) supplementation", 
                   "Problem-based learning (PBL)", 
                   "Cognitive Behavioral Therapy"),
  Comparator = c("Control groups varied", 
                 "Reference standard", 
                 "Placebo/Standard care", 
                 "Lecture-based learning (LBL)", 
                 "Waitlist/Standard care"),
  Outcomes = c("Reduction in depressive symptoms (Cohen's d)", 
               "Sensitivity and Specificity", 
               "Cholesterol levels (WMD)", 
               "Theoretical knowledge scores (SMD)", 
               "Depression scores (SMD)"),
  Disease = c("Depression following TBI", 
              "Retinal detachment", 
              "Dyslipidemia", 
              "Pediatric medical education", 
              "Major Depressive Disorder"),
  Clinical_Department = c("Neuropsychiatry", 
                          "Emergency Medicine", 
                          "Pharmacology", 
                          "Pediatrics", 
                          "Psychiatry"),
  Literature_Abbreviation = c("Slowinski 2019", 
                              "Gottlieb 2019", 
                              "Haghighatdoost 2019", 
                              "Ma 2019", 
                              "Smith 2020"),
  PMID = c(30636565, 30636351, 30633888, 30633204, 12345678),
  # 为可视化添加数值型数据列
  Effect_Size = c(-0.49, 94.2, -10.18, 1.15, -0.75), # Cohen's d, Sensitivity, WMD, SMD, SMD
  CI_Lower = c(-0.96, 78.4, -16.16, 0.79, -1.10),
  CI_Upper = c(-0.02, 98.6, -4.20, 1.52, -0.40),
  P_Value = c(0.02, 0.001, 0.001, 0.00001, 0.001),
  Num_Studies = c(12, 11, 12, 12, 10),
  Total_Sample_Size = c(500, 844, 1200, 1003, 800), # 估算或提取的样本量
  Outcome_Type = c("Mental Health", "Diagnostic Accuracy", "Biomarker", "Academic Performance", "Mental Health"),
  stringsAsFactors = FALSE
)



####################### data1############


meta_db1 <- data.frame(
  Participants = c("Patients with depression following TBI; 12 studies", 
                   "844 patients presenting with ocular complaints in emergency settings", 
                   "Participants from 12 RCTs including diabetic and non-diabetic subjects",
                   "1003 medical students enrolled in 12 RCTs",
                   "9443 participants undergoing PCI classified by SYNTAX Score II",
                   "2361 participants with moderate to severe plaque psoriasis",
                   "577 participants from 10 RCTs",
                   "Children aged 1-5 years; sample size ranged from 258 to 895",
                   "1500 resected pancreatic cancer patients",
                   "1237 patients across 25 RCTs undergoing cataract surgery",
                   "1804 women with non-severe hypertensive disorders of pregnancy",
                   "Human study populations from 85 studies globally",
                   "10,823 infertile male participants (5,257 smokers vs 5,566 non-smokers)",
                   "12,315 individuals with subclinical hypothyroidism",
                   "Adults with chronic orofacial pain; 14 trials",
                   "11,929 patients presenting to ED with acute chest pain",
                   "1,849 adult surgical patients requiring general anesthesia",
                   "15,862 patients with acute Achilles tendon ruptures",
                   "5,827 HIV-infected adults receiving antiretroviral therapy"),
  
  Intervention = c("Pharmacological treatments for depression post-TBI",
                   "Point-of-care ocular ultrasound",
                   "Alpha-lipoic acid (ALA) supplementation",
                   "Problem-based learning (PBL) teaching model",
                   "SYNTAX Score II as predictive tool for mortality risk",
                   "Secukinumab 150 mg dose",
                   "Hesperidin supplementation",
                   "Exposure to interpersonal stress via separation-reunion procedures",
                   "Assessment of microvessel density (MVD)",
                   "Multifocal intraocular lenses (IOLs)",
                   "Antihypertensive drug therapy",
                   "Not applicable (systematic review of subtype distribution)",
                   "Exposure to tobacco smoking",
                   "Levothyroxine therapy",
                   "Self-management interventions combining physical and psychosocial self-regulation",
                   "Serial high-sensitivity cardiac troponin T measurements",
                   "Preoperative intravenous dexamethasone",
                   "Operative treatment",
                   "Antiretroviral therapy"),
  
  Comparator = c("Control groups varied",
                 "Reference standard diagnostic methods",
                 "Placebo or standard care",
                 "Traditional lecture-based learning (LBL)",
                 "Low SYNTAX Score II groups",
                 "Secukinumab 300 mg dose",
                 "Placebo or standard care",
                 "Baseline physiological activity without stress exposure",
                 "Low-MVD expression groups",
                 "Standard monofocal IOLs or monovision",
                 "Placebo or no treatment",
                 "Not applicable",
                 "Non-smoking infertile males",
                 "Euthyroid healthy controls",
                 "Usual care",
                 "Standard diagnostic evaluation",
                 "Non-analgesic methods",
                 "Nonoperative treatment",
                 "Male HIV-infected adults"),
  
  Outcomes = c("Reduction in depressive symptoms (Cohen's d = -0.49)",
               "Sensitivity 94.2%, specificity 96.3%",
               "Reduction in serum total cholesterol (WMD = -10.18 mg/dL)",
               "Theoretical knowledge scores (SMD = 1.15)",
               "All-cause mortality risk ratios",
               "Risk of adverse events",
               "No significant effect on lipid profile or blood pressure",
               "Physiological reactivity measures",
               "Overall survival and disease-free survival hazard ratios",
               "Uncorrected near vision and spectacle independence",
               "Maternal and neonatal outcomes",
               "Prevalence of Cryptosporidium parvum IIc subtype",
               "Semen parameters and morphological defects",
               "Risk of depression and response to levothyroxine",
               "Pain intensity and depression scores",
               "Sensitivity and specificity for AMI diagnosis",
               "Incidence and severity of postoperative sore throat",
               "Re-rupture and complication rates",
               "Food insecurity odds ratio"),
  
  Disease = c("Depression following TBI",
              "Retinal detachment",
              "Dyslipidemia",
              "Pediatric medical education",
              "Coronary artery disease requiring PCI",
              "Moderate to severe plaque psoriasis",
              "Lipid profile and blood pressure related conditions",
              "Infant attachment insecurity",
              "Pancreatic cancer",
              "Cataract requiring surgery",
              "Non-severe hypertensive disorders of pregnancy",
              "Cryptosporidium parvum infection",
              "Male infertility",
              "Subclinical hypothyroidism with coexistent depression",
              "Chronic orofacial pain",
              "Acute myocardial infarction",
              "Postoperative sore throat",
              "Acute Achilles tendon rupture",
              "HIV infection"),
  
  Clinical_Department = c("Neuropsychiatry",
                          "Emergency Medicine",
                          "Pharmacology",
                          "Pediatrics",
                          "Cardiology",
                          "Dermatology",
                          "Not specified",
                          "Developmental Psychology",
                          "Oncology",
                          "Ophthalmology",
                          "Obstetrics",
                          "Infectious Diseases",
                          "Internal Medicine",
                          "Endocrinology",
                          "Dentistry",
                          "Cardiology",
                          "Anesthesiology",
                          "Orthopedics",
                          "Public Health"),
  
  Literature_Abbreviation = c("Slowinski 2019",
                              "Gottlieb 2019",
                              "Haghighatdoost 2019",
                              "Ma 2019",
                              "Yang 2019",
                              "Zhang 2019",
                              "Not specified",
                              "Groh 2019",
                              "Ntellas 2019",
                              "Khandelwal 2019",
                              "Ogura 2019",
                              "King 2019",
                              "Bundhun 2019",
                              "Loh 2019",
                              "Aggarwal 2019",
                              "Arslan 2020",
                              "Kuriyama 2019",
                              "Ochen 2019",
                              "Boneya 2019"),
  
  PMID = c(30636565, 30636351, 30633888, 30633204, 30633200, 30633199, 
           30632207, 30629289, 30629030, 30627791, 30626932, 30621759, 
           30621647, 30621645, 30620145, 30618277, 30617677, 30617123, 30615692),
  
  Effect_Size = c(-0.49, 94.2, -10.18, 1.15, 2.65, 1.00, -1.04, -0.06, 2.0, -0.26, 
                  0.70, 19.0, 1.29, 2.35, -0.32, 96.7, 0.62, 0.43, 1.53),
  
  CI_Lower = c(-0.96, 78.4, -16.16, 0.79, 1.05, 0.96, -5.65, NA, 1.57, -0.37, 
               0.04, 12.9, 1.05, 1.84, -0.47, 92.3, 0.51, 0.31, 1.29),
  
  CI_Upper = c(-0.02, 98.6, -4.20, 1.52, 6.73, 1.05, 3.57, NA, 2.54, -0.15, 
               11.45, 25.9, 1.59, 3.02, -0.17, 99.3, 0.75, 0.60, 1.83),
  
  P_Value = c(0.02, 0.001, 0.001, 0.00001, 0.04, 0.94, NA, NA, 0.001, NA, 
              NA, NA, 0.02, 0.001, NA, NA, NA, 0.001, NA),
  
  Num_Studies = c(12, 11, 12, 12, NA, 7, 10, NA, NA, 25, 14, 85, NA, NA, 14, NA, 4, 29, NA),
  
  Total_Sample_Size = c(500, 844, 1200, 1003, 9443, 2361, 577, 895, 1500, 1237, 
                        1804, NA, 10823, 12315, NA, 11929, 1849, 15862, 5827),
  
  Outcome_Type = c("Mental Health", "Diagnostic Accuracy", "Biomarker", "Academic Performance", 
                   "Mortality Risk", "Safety", "Biomarker", "Physiological Measures", 
                   "Survival", "Visual Outcomes", "Obstetric Outcomes", "Prevalence", 
                   "Semen Quality", "Mental Health", "Pain Measures", "Diagnostic Accuracy", 
                   "Postoperative Complications", "Orthopedic Outcomes", "Public Health"),
  
  stringsAsFactors = FALSE
)

##################data2#####################

meta_db2 <- data.frame(
  Participants = c("5827 HIV-infected adults aged >18 years receiving ART",
                   "Participants from Colombia in observational studies",
                   "86 patients with cancer pain from RCTs",
                   "Patients with PCOS from multiple studies",
                   "896 cases with refractory idiopathic epistaxis",
                   "8408 patients with symptomatic ICAS from 92 studies",
                   "Older people with dementia; 26 studies",
                   "Patients with chronic subdural hematoma; 24 studies",
                   "2185 prostate cancer patients from 7 studies",
                   "728 patients with nonsyndromic craniosynostosis",
                   "261,660 adults from 68 studies",
                   "Patients with premature ejaculation; 19 RCTs",
                   "Patients with androgenetic alopecia",
                   "Children and adolescents receiving psychotherapy; 35 studies",
                   "4613 patients with NSCLC from 13 studies",
                   "Patients undergoing immediate implant placement; 7 studies",
                   "141 pediatric cases with suspected cholesteatoma",
                   "7849 patients with OIC from 31 RCTs",
                   "Older adults from 40 observational studies",
                   "779 peri- or postmenopausal women from 5 RCTs",
                   "Athletes with intellectual disabilities; 16 studies",
                   "375 stable phase patients with schizophrenia",
                   "98,436 participants from 154 samples",
                   "88 pregnant women with cervical cancer",
                   "1710 patients with distal fibular fractures",
                   "1102 type 2 diabetic cases and 1078 controls",
                   "Published patient cases with BCS1L mutations",
                   "Patients with incidental gallbladder cancer",
                   "Patients undergoing orthotopic liver transplantation",
                   "Patients undergoing oral surgery on antiplatelet therapy",
                   "553 patients with IIM-ILD"),
  
  Intervention = c("Antiretroviral therapy",
                   "Not applicable (systematic review)",
                   "Lidocaine infusion 4-5 mg/kg",
                   "Measurement of circulating betatrophin levels",
                   "Sphenopalatine artery surgery",
                   "Endovascular stenting",
                   "Use of international tools to identify inappropriate prescribing",
                   "Antithrombotic drugs",
                   "Assessment of PITX2 gene promoter methylation",
                   "Preoperative CT scan",
                   "Exposure to childhood maltreatment",
                   "Paroxetine administration",
                   "Platelet-rich plasma injections",
                   "Psychotherapy interventions",
                   "Nab-paclitaxel plus carboplatin",
                   "Immediate implant placement with regenerative procedure",
                   "Non-EPI DW-MRI",
                   "Peripherally acting μ-opioid receptor antagonists",
                   "Functional Reach Test",
                   "Equol supplementation or soy isoflavone intake",
                   "Not applicable (prevalence study)",
                   "Not applicable (neuropsychological assessment)",
                   "Exposure to major life events",
                   "Neoadjuvant platinum-based chemotherapy",
                   "Intramedullary fixation",
                   "Measurement of circulatory apelin levels",
                   "No experimental intervention",
                   "Reresection for cancers invading muscle layer",
                   "Initial portal reperfusion",
                   "Continuation of antiplatelet therapy",
                   "Immunosuppressive therapies"),
  
  Comparator = c("Comparison between female and male HIV-infected adults",
                 "Not applicable",
                 "Placebo or dexmedetomidine",
                 "Non-PCOS control groups",
                 "Comparison between cauterization and ligation",
                 "Medical management or standard care",
                 "Not applicable",
                 "Patients not receiving antithrombotic drugs",
                 "Patients with low PITX2 methylation status",
                 "Clinical examination alone",
                 "Adults not exposed to childhood maltreatment",
                 "Placebo and various active comparators",
                 "Placebo (half-head design)",
                 "Varying levels of therapist adherence/competence",
                 "Solvent-based paclitaxel plus carboplatin",
                 "Immediate implant placement without regenerative procedure",
                 "Second-look surgery",
                 "Placebo",
                 "Not applicable",
                 "Placebo or no equol supplementation",
                 "Not applicable",
                 "Healthy control subjects",
                 "Control groups without life events",
                 "No explicit comparator",
                 "Plate fixation",
                 "Healthy control subjects",
                 "No comparator",
                 "Cholecystectomy alone for T1a or less",
                 "Simultaneous or initial artery reperfusion",
                 "Discontinuation of antiplatelet therapy",
                 "Different immunosuppressive agents"),
  
  Outcomes = c("Food insecurity OR = 1.53 (95% CI: 1.29-1.83)",
               "Chagas disease prevalence = 2.0% (95% CI: 1.0-4.0)",
               ">50% reduction in cancer pain with lidocaine",
               "Betatrophin SMD = 0.73 (95% CI: 0.22-1.24)",
               "Rebleeding rates: entire cohort 13.4% (95% CI: 10.0-17.8)",
               "Short-term stroke/death rate: 6.68% (95% CI: 5.60-8.36%)",
               "PIP prevalence 14-74% in dementia patients",
               "Recurrence OR = 1.30 (95% CI: 1.11-1.52)",
               "BCR HR = 2.71 (95% CI: 2.21-3.31)",
               "Physical examination concordance 97.9%",
               "Suicide attempts OR: sexual abuse 3.17 (95% CI: 2.76-3.64)",
               "IELT significantly increased with paroxetine",
               "Hair density mean difference = 25.61 hair/cm²",
               "Small positive adherence-outcome relationship",
               "ORR RR = 1.31, PFS HR = 0.89, OS HR = 0.93",
               "Horizontal ridge shrinkage WMD = 0.84 mm",
               "Sensitivity 89.4%, specificity 92.9%",
               "SBM mean difference = 1.43, responder RR = 1.81",
               "Functional Reach normative data: community 26.6 cm",
               "Significant reduction in hot flash scores",
               "Dental caries prevalence 36.5% (95% CI: 30.6-42.7)",
               "Worse executive function in all BADS subtests",
               "Changes in psychological well-being subdomains",
               "Overall survival median not reached",
               "Wound complications OR = 0.11, implant removal OR = 0.54",
               "Apelin SMD = 2.136 (95% CI: 1.580-2.693)",
               "Phenotypic spectrum of BCS1L mutations",
               "5-year survival up to 100% for T1a or less",
               "Non-anastomotic biliary strictures OR = 0.40",
               "Bleeding events RR = 0.97 (95% CI: 0.41-2.34)",
               "Functional improvement rates for various immunosuppressants"),
  
  Disease = c("HIV infection",
              "Chagas disease",
              "Cancer pain",
              "Polycystic ovary syndrome",
              "Refractory idiopathic epistaxis",
              "Symptomatic intracranial arterial stenosis",
              "Dementia",
              "Chronic subdural hematoma",
              "Prostate cancer",
              "Nonsyndromic craniosynostosis",
              "Childhood maltreatment and adult suicidality",
              "Premature ejaculation",
              "Androgenetic alopecia",
              "Psychotherapy for children and adolescents",
              "Non-small cell lung cancer",
              "Minor bone defect at implant site",
              "Residual and recurrent cholesteatoma",
              "Opioid-induced constipation",
              "Balance and falls risk in older adults",
              "Menopausal symptoms",
              "Dental caries",
              "Schizophrenia",
              "Psychological well-being changes",
              "Cervical cancer",
              "Distal fibular fractures",
              "Type 2 diabetes mellitus",
              "BCS1L Mitopathies",
              "Incidental gallbladder cancer",
              "Non-anastomotic biliary strictures",
              "Oral surgery on antiplatelet therapy",
              "Idiopathic inflammatory myositis-associated ILD"),
  
  Clinical_Department = c("Public Health",
                          "Epidemiology, Parasitology",
                          "Palliative Care",
                          "Gynecology/Endocrinology",
                          "Otorhinolaryngology",
                          "Neurosurgery",
                          "Geriatrics",
                          "Geriatrics, Neurosurgery",
                          "Medical Oncology",
                          "Plastic and Reconstructive Surgery",
                          "Psychology",
                          "Urology & Nephrology",
                          "Dermatology",
                          "Child and Adolescent Psychiatry",
                          "Oncology",
                          "Periodontology",
                          "Otolaryngology",
                          "Gastroenterology, Hepatology",
                          "Geriatrics",
                          "Gynecology/Women's Health",
                          "Dentistry",
                          "Psychiatry",
                          "Psychology",
                          "Obstetrics and Gynecology",
                          "Trauma Surgery",
                          "Clinical Biochemistry",
                          "Medical Genetics",
                          "Surgery",
                          "Hepatobiliary Surgery",
                          "Oral Surgery",
                          "Internal and Vascular Medicine; Respiratory Medicine"),
  
  Literature_Abbreviation = c("Boneya 2019",
                              "Olivera 2019",
                              "Lee 2019",
                              "Varikasuvu 2019",
                              "Kitamura 2019",
                              "Wang 2020",
                              "Hukins 2019",
                              "Wang 2019",
                              "Jiang 2019",
                              "Alnaif 2019",
                              "Angelakis 2019",
                              "Zhang 2019",
                              "Gupta 2019",
                              "Collyer 2020",
                              "Tan 2019",
                              "Lee 2019",
                              "Bazzi 2019",
                              "Nishie 2019",
                              "Rosa 2019",
                              "Daily 2019",
                              "Azeredo 2018",
                              "Thai 2019",
                              "Mangelsdorf 2019",
                              "Song 2018",
                              "Tas 2019",
                              "Noori-Zadeh 2019",
                              "Baker 2019",
                              "Søreide 2019",
                              "Bekheit 2019",
                              "Villanueva 2019",
                              "Barba 2019"),
  
  PMID = c(30615692, 30615644, 30614748, 30614305, 30613985, 30612142, 
           30610274, 30608437, 30608394, 30608374, 30608046, 30606186, 
           30606055, 30604132, 30600739, 30600736, 30599286, 30597600, 
           30593986, 30592686, 30592320, 30590277, 30589274, 30587930, 
           30583773, 30583036, 30582773, 30582640, 30579736, 30573718, 30572131),
  
  Effect_Size = c(1.53, 2.0, NA, 0.73, 13.4, 6.68, NA, 1.30, 2.71, 97.9, 
                  3.17, NA, 25.61, NA, 1.31, 0.84, 89.4, 1.43, 26.6, NA, 
                  36.5, NA, NA, NA, 0.11, 2.136, NA, NA, 0.40, 0.97, NA),
  
  CI_Lower = c(1.29, 1.0, NA, 0.22, 10.0, 5.60, NA, 1.11, 2.21, NA, 
               2.76, NA, 4.45, NA, NA, 0.53, 51.9, 1.18, 25.14, NA, 
               30.6, NA, NA, NA, 0.04, 1.580, NA, NA, NA, 0.41, NA),
  
  CI_Upper = c(1.83, 4.0, NA, 1.24, 17.8, 8.36, NA, 1.52, 3.31, NA, 
               3.64, NA, 46.77, NA, NA, 1.14, 98.5, 1.68, 28.06, NA, 
               42.7, NA, NA, NA, 0.25, 2.693, NA, NA, NA, 2.34, NA),
  
  P_Value = c(NA, 0.001, 0.05, 0.005, NA, 0.018, NA, 0.001, 0.000, NA, 
              NA, 0.05, 0.02, NA, NA, 0.00001, NA, NA, NA, NA, 
              NA, NA, NA, NA, 0.01, 0.000, NA, NA, 0.14, 0.09, NA),
  
  Num_Studies = c(NA, 16, 5, NA, NA, 92, 26, 24, 7, 11, 68, 19, NA, 35, 13, 7, 10, 31, 40, 5, 16, 10, 122, NA, NA, 16, NA, NA, 7, 5, NA),
  
  Total_Sample_Size = c(5827, NA, 86, NA, 896, 8408, NA, NA, 2185, 728, 261660, NA, NA, NA, 4613, NA, 141, 7849, NA, 779, NA, 375, 98436, 88, 1710, 2180, NA, NA, NA, NA, 553),
  
  Outcome_Type = c("Public Health", "Prevalence", "Pain Relief", "Biomarker", 
                   "Surgical Outcomes", "Procedure Safety", "Prescribing Patterns", 
                   "Recurrence Risk", "Prognostic Biomarker", "Diagnostic Accuracy", 
                   "Mental Health", "Sexual Function", "Dermatological", 
                   "Therapeutic Process", "Oncological Outcomes", "Dental Outcomes", 
                   "Diagnostic Accuracy", "Gastrointestinal", "Functional Assessment", 
                   "Menopausal Symptoms", "Dental Health", "Neuropsychological", 
                   "Psychological Well-being", "Oncological Outcomes", 
                   "Orthopedic Outcomes", "Biomarker", "Genetic", "Surgical Outcomes", 
                   "Surgical Complications", "Surgical Safety", "Treatment Response"),
  
  stringsAsFactors = FALSE
)


################## data3##########
meta_db3 <- data.frame(
  Participants = c("43,721 patients with type 2 diabetes mellitus",
                   "6,836 participants from 18 studies",
                   "1,091 adolescents with overweight/obesity",
                   "Preterm infants ≤37 weeks gestational age and parents",
                   "1,637 participants with F508del-CFTR homozygous mutation",
                   "387 participants with low back pain",
                   "People with dementia from 8 articles",
                   "Adolescents and adults with anorexia nervosa",
                   "Patients with ameloblastoma from 20 studies",
                   "299 patients undergoing pancreaticoduodenectomy",
                   "3,141 patients at risk for chronic liver disease",
                   "9,005 patients undergoing cardiac surgery",
                   "2,667 teeth from 19 studies",
                   "475 patients with pityriasis rubra pilaris",
                   "Healthy volunteers from 8 studies",
                   "Adults with MDD and bipolar disorder",
                   "3,977 adult patients with diabetes",
                   "25,002 individuals aged ≥55 years",
                   "Adults from 28 RCTs",
                   "Cognitively impaired subjects from 53 studies",
                   "1,736 cases of endometrial hyperplasia"),
  
  Intervention = c("Sodium-glucose cotransporter 2 inhibitors (SGLT2is)",
                   "Skin self-examination interventions",
                   "Structured exercise interventions",
                   "Family-centred care interventions",
                   "CFTR corrector and potentiator combination therapy",
                   "Hip-targeted physical therapy",
                   "Pet robot intervention",
                   "Individual and family-based therapy",
                   "Radical treatment of ameloblastoma",
                   "Enteral immunonutrition",
                   "Anti-platelet agents",
                   "Restrictive RBC transfusion strategy",
                   "Surgical crown or root resection",
                   "Systemic treatments for PRP",
                   "Junctional tourniquet devices",
                   "Electroconvulsive therapy",
                   "Insulin glargine 300 U/ml",
                   "Not applicable (prevalence study)",
                   "Resveratrol supplementation",
                   "APOE genotype status assessment",
                   "PTEN immunohistochemical assessment"),
  
  Comparator = c("Placebo control groups",
                 "Control groups with varied treatments",
                 "No structured exercise",
                 "Standard care in NICU",
                 "Basic treatment without CFTR therapy",
                 "Standard care or no hip-targeted intervention",
                 "Control groups from RCTs",
                 "Standard care or no treatment",
                 "Conservative treatment of ameloblastoma",
                 "Standard care or no immunonutrition",
                 "Patients without anti-platelet agents",
                 "Liberal RBC transfusion strategy",
                 "Comparison between CR and RR procedures",
                 "Comparison across different systemic therapies",
                 "No active comparator",
                 "Standard care or no treatment",
                 "Insulin glargine 100 U/ml",
                 "Not applicable",
                 "Placebo or no resveratrol",
                 "APOE ε4 non-carriers",
                 "Histological diagnosis as reference"),
  
  Outcomes = c("eGFR changes: initial decrease then long-term improvement",
               "Increased SSE activity at short term (OR=2.31)",
               "Weight loss and BMI decrease with exercise dose",
               "Improved weight gain, reduced readmission, increased parental satisfaction",
               "Improved FEV1, CFQ-R score, and BMI",
               "Trivial effect for pain, small effect for disability",
               "Decreased behavioral and psychological symptoms",
               "Drop-out rates and treatment outcome predictors",
               "Lower recurrence with radical treatment",
               "Reduced infectious complications, shortened hospital stay",
               "32% decreased odds of hepatic fibrosis (OR=0.68)",
               "No mortality difference, shorter ICU stay with liberal strategy",
               "85.6% combined survival rate for treated teeth",
               "Excellent response rates for various systemic therapies",
               "Effectiveness rates for arterial occlusion",
               "Higher response rates in BDD, similar remission rates",
               "Reduced nocturnal hypoglycemia events",
               "0.7% prevalence of retinal vein occlusion",
               "Reductions in body weight, BMI, and waist circumference",
               "No association with affective symptoms",
               "Diagnostic accuracy metrics for PTEN immunohistochemistry"),
  
  Disease = c("Type 2 diabetes mellitus with/without kidney disease",
              "Skin cancer",
              "Overweight and obesity in adolescents",
              "Preterm infants",
              "Cystic fibrosis with F508del mutation",
              "Low back pain",
              "Dementia",
              "Anorexia nervosa",
              "Ameloblastoma",
              "Pancreaticoduodenectomy patients",
              "Hepatic fibrosis",
              "Cardiac surgery patients",
              "Teeth requiring surgical intervention",
              "Pityriasis rubra pilaris",
              "Junctional vascular trauma",
              "Major depressive disorder and bipolar disorder",
              "Type 1 and type 2 diabetes",
              "Retinal vein occlusion",
              "Obesity",
              "Mild cognitive impairment and Alzheimer's disease",
              "Endometrial hyperplasia"),
  
  Clinical_Department = c("Endocrinology",
                          "Dermatology",
                          "Exercise and Sport Science",
                          "Neonatology",
                          "Respiratory and Critical Care Medicine",
                          "Physical Therapy",
                          "Psychiatry",
                          "Psychiatry",
                          "Oral and Maxillofacial Surgery",
                          "General Surgery",
                          "Gastroenterology and Hepatology",
                          "Cardiology",
                          "Endodontics",
                          "Dermatology, Venereology, Allergology",
                          "Surgery",
                          "Psychiatry",
                          "Endocrinology",
                          "Ophthalmology",
                          "Endocrinology and Metabolism",
                          "Psychiatry and Neuropsychology",
                          "Gynecology and Obstetrics"),
  
  Literature_Abbreviation = c("Wang 2019",
                              "Ersser 2018",
                              "Stoner 2019",
                              "Ding 2019",
                              "Wu 2019",
                              "Bernet 2019",
                              "Leng 2019",
                              "Gregertsen 2019",
                              "Hendra 2019",
                              "Guan 2019",
                              "Iqbal 2019",
                              "Kheiri 2019",
                              "Setzer 2019",
                              "Kromer 2019",
                              "Smith 2019",
                              "Bahji 2019",
                              "Díez-Fernández 2019",
                              "Li 2019",
                              "Mousavi 2019",
                              "Banning 2019",
                              "Raffone 2019"),
  
  PMID = c(30565382, 30561006, 30560421, 30554939, 30554331, 30553988, 
           30553098, 30551081, 30548549, 30541005, 30539518, 30511259, 
           30527594, 30520557, 30507857, 30506992, 30506484, 30517942, 
           30515938, 30513312, 30511743),
  
  Effect_Size = c(-4.63, 2.31, -0.33, 4.57, 2.38, NA, NA, NA, 0.08, 0.58, 
                  0.68, 1.03, 85.6, 42.0, 52.0, 0.73, 0.81, 0.7, -0.51, NA, 54.0),
  
  CI_Lower = c(NA, 1.90, 0.08, 2.80, 1.62, NA, NA, NA, NA, 0.37, 0.56, 0.74, 
               76.7, NA, 15.0, 0.56, 0.69, 0.5, -0.94, NA, 50.0),
  
  CI_Upper = c(NA, 2.82, 0.59, 6.34, 3.15, NA, NA, NA, NA, 0.92, 0.82, 1.45, 
               91.5, NA, 87.0, 0.95, 0.95, 0.9, -0.09, NA, 59.0),
  
  P_Value = c(NA, NA, NA, 0.001, 0.00001, NA, NA, NA, NA, 0.02, 0.0001, 0.86, 
              0.89, NA, NA, 0.02, NA, NA, 0.02, NA, NA),
  
  Num_Studies = c(NA, 18, 20, 19, 5, 6, 8, 27, 20, 4, 4, 9, 19, 182, 8, NA, NA, 4, 28, 53, 27),
  
  Total_Sample_Size = c(43721, 6836, 1091, NA, 1637, 387, NA, NA, NA, 299, 3141, 9005, 
                        2667, 475, NA, 2247, 3977, 25002, NA, NA, 1736),
  
  Outcome_Type = c("Renal Function", "Preventive Behavior", "Weight Management", 
                   "Neonatal Outcomes", "Respiratory Function", "Pain Management", 
                   "Behavioral Symptoms", "Treatment Adherence", "Surgical Outcomes", 
                   "Postoperative Complications", "Fibrosis Risk", "Transfusion Outcomes", 
                   "Dental Outcomes", "Treatment Response", "Device Effectiveness", 
                   "Mental Health", "Glycemic Control", "Prevalence", "Metabolic Parameters", 
                   "Neuropsychiatric Symptoms", "Diagnostic Accuracy"),
  
  stringsAsFactors = FALSE
)

#############data4#############


meta_db4 <- data.frame(
  Participants = c("5827 HIV-infected adults aged >18 years receiving ART",
                   "Participants from Colombia in observational studies",
                   "86 patients with cancer pain from RCTs",
                   "Patients with PCOS from multiple studies",
                   "896 cases with refractory idiopathic epistaxis",
                   "8408 patients with symptomatic ICAS from 92 studies",
                   "Older people with dementia; 26 studies",
                   "Patients with chronic subdural hematoma; 24 studies",
                   "2185 prostate cancer patients from 7 studies",
                   "728 patients with nonsyndromic craniosynostosis",
                   "261,660 adults from 68 studies",
                   "Patients with premature ejaculation; 19 RCTs",
                   "Patients with androgenetic alopecia",
                   "Children and adolescents receiving psychotherapy; 35 studies",
                   "4613 patients with NSCLC from 13 studies",
                   "Patients undergoing immediate implant placement; 7 studies",
                   "141 pediatric cases with suspected cholesteatoma",
                   "7849 patients with OIC from 31 RCTs",
                   "Older adults from 40 observational studies",
                   "779 peri- or postmenopausal women from 5 RCTs",
                   "Athletes with intellectual disabilities; 16 studies",
                   "375 stable phase patients with schizophrenia",
                   "98,436 participants from 154 samples",
                   "88 pregnant women with cervical cancer",
                   "1710 patients with distal fibular fractures",
                   "1102 type 2 diabetic cases and 1078 controls",
                   "Published patient cases with BCS1L mutations",
                   "Patients with incidental gallbladder cancer",
                   "Patients undergoing orthotopic liver transplantation",
                   "Patients undergoing oral surgery on antiplatelet therapy",
                   "553 patients with IIM-ILD"),
  
  Intervention = c("Antiretroviral therapy",
                   "Not applicable (systematic review)",
                   "Lidocaine infusion 4-5 mg/kg",
                   "Measurement of circulating betatrophin levels",
                   "Sphenopalatine artery surgery",
                   "Endovascular stenting",
                   "Use of international tools to identify inappropriate prescribing",
                   "Antithrombotic drugs",
                   "Assessment of PITX2 gene promoter methylation",
                   "Preoperative CT scan",
                   "Exposure to childhood maltreatment",
                   "Paroxetine administration",
                   "Platelet-rich plasma injections",
                   "Psychotherapy interventions",
                   "Nab-paclitaxel plus carboplatin",
                   "Immediate implant placement with regenerative procedure",
                   "Non-EPI DW-MRI",
                   "Peripherally acting μ-opioid receptor antagonists",
                   "Functional Reach Test",
                   "Equol supplementation or soy isoflavone intake",
                   "Not applicable (prevalence study)",
                   "Not applicable (neuropsychological assessment)",
                   "Exposure to major life events",
                   "Neoadjuvant platinum-based chemotherapy",
                   "Intramedullary fixation",
                   "Measurement of circulatory apelin levels",
                   "No experimental intervention",
                   "Reresection for cancers invading muscle layer",
                   "Initial portal reperfusion",
                   "Continuation of antiplatelet therapy",
                   "Immunosuppressive therapies"),
  
  Comparator = c("Comparison between female and male HIV-infected adults",
                 "Not applicable",
                 "Placebo or dexmedetomidine",
                 "Non-PCOS control groups",
                 "Comparison between cauterization and ligation",
                 "Medical management or standard care",
                 "Not applicable",
                 "Patients not receiving antithrombotic drugs",
                 "Patients with low PITX2 methylation status",
                 "Clinical examination alone",
                 "Adults not exposed to childhood maltreatment",
                 "Placebo and various active comparators",
                 "Placebo (half-head design)",
                 "Varying levels of therapist adherence/competence",
                 "Solvent-based paclitaxel plus carboplatin",
                 "Immediate implant placement without regenerative procedure",
                 "Second-look surgery",
                 "Placebo",
                 "Not applicable",
                 "Placebo or no equol supplementation",
                 "Not applicable",
                 "Healthy control subjects",
                 "Control groups without life events",
                 "No explicit comparator",
                 "Plate fixation",
                 "Healthy control subjects",
                 "No comparator",
                 "Cholecystectomy alone for T1a or less",
                 "Simultaneous or initial artery reperfusion",
                 "Discontinuation of antiplatelet therapy",
                 "Different immunosuppressive agents"),
  
  Outcomes = c("Food insecurity OR = 1.53 (95% CI: 1.29-1.83)",
               "Chagas disease prevalence = 2.0% (95% CI: 1.0-4.0)",
               ">50% reduction in cancer pain with lidocaine",
               "Betatrophin SMD = 0.73 (95% CI: 0.22-1.24)",
               "Rebleeding rates: entire cohort 13.4% (95% CI: 10.0-17.8)",
               "Short-term stroke/death rate: 6.68% (95% CI: 5.60-8.36%)",
               "PIP prevalence 14-74% in dementia patients",
               "Recurrence OR = 1.30 (95% CI: 1.11-1.52)",
               "BCR HR = 2.71 (95% CI: 2.21-3.31)",
               "Physical examination concordance 97.9%",
               "Suicide attempts OR: sexual abuse 3.17 (95% CI: 2.76-3.64)",
               "IELT significantly increased with paroxetine",
               "Hair density mean difference = 25.61 hair/cm²",
               "Small positive adherence-outcome relationship",
               "ORR RR = 1.31, PFS HR = 0.89, OS HR = 0.93",
               "Horizontal ridge shrinkage WMD = 0.84 mm",
               "Sensitivity 89.4%, specificity 92.9%",
               "SBM mean difference = 1.43, responder RR = 1.81",
               "Functional Reach normative data: community 26.6 cm",
               "Significant reduction in hot flash scores",
               "Dental caries prevalence 36.5% (95% CI: 30.6-42.7)",
               "Worse executive function in all BADS subtests",
               "Changes in psychological well-being subdomains",
               "Overall survival median not reached",
               "Wound complications OR = 0.11, implant removal OR = 0.54",
               "Apelin SMD = 2.136 (95% CI: 1.580-2.693)",
               "Phenotypic spectrum of BCS1L mutations",
               "5-year survival up to 100% for T1a or less",
               "Non-anastomotic biliary strictures OR = 0.40",
               "Bleeding events RR = 0.97 (95% CI: 0.41-2.34)",
               "Functional improvement rates for various immunosuppressants"),
  
  Disease = c("HIV infection",
              "Chagas disease",
              "Cancer pain",
              "Polycystic ovary syndrome",
              "Refractory idiopathic epistaxis",
              "Symptomatic intracranial arterial stenosis",
              "Dementia",
              "Chronic subdural hematoma",
              "Prostate cancer",
              "Nonsyndromic craniosynostosis",
              "Childhood maltreatment and adult suicidality",
              "Premature ejaculation",
              "Androgenetic alopecia",
              "Psychotherapy for children and adolescents",
              "Non-small cell lung cancer",
              "Minor bone defect at implant site",
              "Residual and recurrent cholesteatoma",
              "Opioid-induced constipation",
              "Balance and falls risk in older adults",
              "Menopausal symptoms",
              "Dental caries",
              "Schizophrenia",
              "Psychological well-being changes",
              "Cervical cancer",
              "Distal fibular fractures",
              "Type 2 diabetes mellitus",
              "BCS1L Mitopathies",
              "Incidental gallbladder cancer",
              "Non-anastomotic biliary strictures",
              "Oral surgery on antiplatelet therapy",
              "Idiopathic inflammatory myositis-associated ILD"),
  
  Clinical_Department = c("Public Health",
                          "Epidemiology, Parasitology",
                          "Palliative Care",
                          "Gynecology/Endocrinology",
                          "Otorhinolaryngology",
                          "Neurosurgery",
                          "Geriatrics",
                          "Geriatrics, Neurosurgery",
                          "Medical Oncology",
                          "Plastic and Reconstructive Surgery",
                          "Psychology",
                          "Urology & Nephrology",
                          "Dermatology",
                          "Child and Adolescent Psychiatry",
                          "Oncology",
                          "Periodontology",
                          "Otolaryngology",
                          "Gastroenterology, Hepatology",
                          "Geriatrics",
                          "Gynecology/Women's Health",
                          "Dentistry",
                          "Psychiatry",
                          "Psychology",
                          "Obstetrics and Gynecology",
                          "Trauma Surgery",
                          "Clinical Biochemistry",
                          "Medical Genetics",
                          "Surgery",
                          "Hepatobiliary Surgery",
                          "Oral Surgery",
                          "Internal and Vascular Medicine; Respiratory Medicine"),
  
  Literature_Abbreviation = c("Boneya 2019",
                              "Olivera 2019",
                              "Lee 2019",
                              "Varikasuvu 2019",
                              "Kitamura 2019",
                              "Wang 2020",
                              "Hukins 2019",
                              "Wang 2019",
                              "Jiang 2019",
                              "Alnaif 2019",
                              "Angelakis 2019",
                              "Zhang 2019",
                              "Gupta 2019",
                              "Collyer 2020",
                              "Tan 2019",
                              "Lee 2019",
                              "Bazzi 2019",
                              "Nishie 2019",
                              "Rosa 2019",
                              "Daily 2019",
                              "Azeredo 2018",
                              "Thai 2019",
                              "Mangelsdorf 2019",
                              "Song 2018",
                              "Tas 2019",
                              "Noori-Zadeh 2019",
                              "Baker 2019",
                              "Søreide 2019",
                              "Bekheit 2019",
                              "Villanueva 2019",
                              "Barba 2019"),
  
  PMID = c(30615692, 30615644, 30614748, 30614305, 30613985, 30612142, 
           30610274, 30608437, 30608394, 30608374, 30608046, 30606186, 
           30606055, 30604132, 30600739, 30600736, 30599286, 30597600, 
           30593986, 30592686, 30592320, 30590277, 30589274, 30587930, 
           30583773, 30583036, 30582773, 30582640, 30579736, 30573718, 30572131),
  
  Effect_Size = c(1.53, 2.0, NA, 0.73, 13.4, 6.68, NA, 1.30, 2.71, 97.9, 
                  3.17, NA, 25.61, NA, 1.31, 0.84, 89.4, 1.43, 26.6, NA, 
                  36.5, NA, NA, NA, 0.11, 2.136, NA, NA, 0.40, 0.97, NA),
  
  CI_Lower = c(1.29, 1.0, NA, 0.22, 10.0, 5.60, NA, 1.11, 2.21, NA, 
               2.76, NA, 4.45, NA, NA, 0.53, 51.9, 1.18, 25.14, NA, 
               30.6, NA, NA, NA, 0.04, 1.580, NA, NA, NA, 0.41, NA),
  
  CI_Upper = c(1.83, 4.0, NA, 1.24, 17.8, 8.36, NA, 1.52, 3.31, NA, 
               3.64, NA, 46.77, NA, NA, 1.14, 98.5, 1.68, 28.06, NA, 
               42.7, NA, NA, NA, 0.25, 2.693, NA, NA, NA, 2.34, NA),
  
  P_Value = c(NA, 0.001, 0.05, 0.005, NA, 0.018, NA, 0.001, 0.000, NA, 
              NA, 0.05, 0.02, NA, NA, 0.00001, NA, NA, NA, NA, 
              NA, NA, NA, NA, 0.01, 0.000, NA, NA, 0.14, 0.09, NA),
  
  Num_Studies = c(NA, 16, 5, NA, NA, 92, 26, 24, 7, 11, 68, 19, NA, 35, 13, 7, 10, 31, 40, 5, 16, 10, 122, NA, NA, 16, NA, NA, 7, 5, NA),
  
  Total_Sample_Size = c(5827, NA, 86, NA, 896, 8408, NA, NA, 2185, 728, 261660, NA, NA, NA, 4613, NA, 141, 7849, NA, 779, NA, 375, 98436, 88, 1710, 2180, NA, NA, NA, NA, 553),
  
  Outcome_Type = c("Public Health", "Prevalence", "Pain Relief", "Biomarker", 
                   "Surgical Outcomes", "Procedure Safety", "Prescribing Patterns", 
                   "Recurrence Risk", "Prognostic Biomarker", "Diagnostic Accuracy", 
                   "Mental Health", "Sexual Function", "Dermatological", 
                   "Therapeutic Process", "Oncological Outcomes", "Dental Outcomes", 
                   "Diagnostic Accuracy", "Gastrointestinal", "Functional Assessment", 
                   "Menopausal Symptoms", "Dental Health", "Neuropsychological", 
                   "Psychological Well-being", "Oncological Outcomes", 
                   "Orthopedic Outcomes", "Biomarker", "Genetic", "Surgical Outcomes", 
                   "Surgical Complications", "Surgical Safety", "Treatment Response"),
  
  stringsAsFactors = FALSE
)






#meta_db <- rbind(meta_db,meta_db2,meta_db3,meta_db4)
meta_db_example <- rbind(meta_db1, meta_db2, meta_db3, meta_db4)
